name: Deploy

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Parse version info from tag
        run: |
          # GITHUB_REF is like refs/tags/v2.3.5, so strip the first 11 chars
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "version=$VERSION" >> $GITHUB_ENV
          echo "version_major=$MAJOR" >> $GITHUB_ENV
          echo "version_minor=$MINOR" >> $GITHUB_ENV
          echo "version_patch=$PATCH" >> $GITHUB_ENV

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of distributionManagement/repository/id
          settings-path: ${{ github.workspace }} # location of settings.xml

      - name: Updating versions in all projects
        run: |
          cd releng
          mvn -B -ntp versions:set -DnewVersion=${{ env.version }}

      - name: Update version.txt in infrastructure-impl
        run: |
          cd infrastructure/infrastructure-impl/src/main/resources
          echo "${{ env.version }}" > version.txt

      - name: Deploy Maven packages
        run: mvn -B -ntp clean deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build Docker image and push to ghcr.io
        run: |
          cd server
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Multiple .jar files in the folder will break Dockerfile
          rm target/*-sources.jar
          IMG=ghcr.io/${{ github.repository }}
          docker build \
            --tag $IMG:${{ env.version }} \
            --tag $IMG:${{ env.version_major }}.${{ env.version_minor }}.latest \
            --tag $IMG:${{ env.version_major }}.latest \
            --tag $IMG:latest \
            .
          docker push --all-tags $IMG
